### ISSUE TITLE
Server Error! Try again later

### ISSUE THREAD

**Issue by sugizo** [shaikhsajid1111/manga-down#2]
**code**
```
from manga_down import mangareader
naruto = mangareader.Manga("naruto")
naruto.get_chapter_list()
```
**result**
```
Server Error!
Try again later
```
at the same time test on browser http://mangareader.cc is alive (can open the site)

**Comment by shaikhsajid1111** [comment]
Bot uses this URL: https://www.mangareader.net/naruto to get manga.
And MangaReader have changed their website domain to https://mangareader.cc
So, bot should visit http://mangareader.cc/manga/naruto.

mangareader bot needs fixes according to new website.

**Comment by sugizo** [comment]
http://mangareader.net is blocked by isp, is there any change in the code above or in manga-down ?
something like preference mangareader.net or mangareader.cc
**e.g.**
`mangareader = ['mangareader.net', 'mangareader.cc']`
so if one failed or error, it will check the others

**Comment by shaikhsajid1111** [comment]
Yeah, http://mangreader.net is down. I have fixed mangareader and pushed changes to GitHub, as well as PyPi

**Comment by sugizo** [comment]
latest update work well
thanks for fast response
