### ISSUE TITLE
invalid literal for int() with base 10: '*'

### ISSUE THREAD

**Issue by sugizo** [shaikhsajid1111/manga-down#3]
**code**
```
manga = mangapanda.Manga("kenji")
manga.download_chapter("*")
```
**result**
`invalid literal for int() with base 10: '*'`

**objective**
want to download all chapter

**question**
how to achieve it using manga-down ?

thx

**Comment by shaikhsajid1111** [comment]
Asterisk won't work for downloading all manga chapters. Actually, there's no feature to download all at once.

However you can use the below code that can code similar thing:
```python 
manga = mangapanda.Manga("kenji")
chapter_list = manga.get_chapter_list()

for chapter in range(len(chapter_list)):
    manga.download_chapter(chapter)
```

But use it at your own risk, you may meet the rate limit feature or your IP address can get block temporarily for sending too many requests.

**Comment by sugizo** [comment]
make sense, thank you for the pointer
