### ISSUE TITLE
run from terminal

### ISSUE THREAD

**Issue by sugizo** [shaikhsajid1111/manga-down#4]
manga-py we can run from terminal
**e.g.** 
`$ manga-py https://mangapanda.onl/chapter/one-piece_122`
**ref**
https://github.com/manga-py/manga-py

is it possible to run manga-down from terminal ?
**e.g.**
`$ manga-down https://mangapanda.onl/chapter/one-piece_122`

thx

**Comment by shaikhsajid1111** [comment]
No, but you can use [argparse ](https://docs.python.org/3/library/argparse.html) which is builtin python module for command-line argument.

**Comment by sugizo** [comment]
yes, you right, forgot about that, another options are to use click, fire, hug, invoke, typer, etc
**e.g. in fire**
```
import fire
from manga_down import *

def dl_mangapanda(manga, chapter):
    manga = mangapanda.Manga(manga)
    manga.download_chapter(chapter)

"""
python manga_down_sh.py dl_mangapanda kenji 1
"""

def dl_mangareader(manga, chapter):
    manga = mangareader.Manga(manga)
    manga.download_chapter(chapter)

"""
python manga_down_sh.py dl_mangareader kenji 1
"""

if __name__ == '__main__':
    fire.Fire()

```

thanks
